/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCustomerStoriesRouteImport } from './routes/_site.customer-stories'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SiteProductsSlugRouteImport } from './routes/_site.products.$slug'
import { Route as SiteSolutionsSlugRouteImport } from './routes/_site.solutions.$slug'
import { Route as AppAssignmentsAssignmentIdRouteImport } from './routes/app.assignments.$assignmentId'
import { Route as AppClassesClassIdRouteImport } from './routes/app.classes.$classId'
import { Route as AppSubmissionsSubmissionIdRouteImport } from './routes/app.submissions.$submissionId'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCustomerStoriesRoute = SiteCustomerStoriesRouteImport.update({
  id: '/customer-stories',
  path: '/customer-stories',
  getParentRoute: () => SiteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SiteProductsSlugRoute = SiteProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSolutionsSlugRoute = SiteSolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AppAssignmentsAssignmentIdRoute =
  AppAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppClassesClassIdRoute = AppClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsSubmissionIdRoute =
  AppSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/customer-stories': typeof SiteCustomerStoriesRoute
  '/api/$': typeof ApiSplatRoute
  '/app/': typeof AppIndexRoute
  '/products/$slug': typeof SiteProductsSlugRoute
  '/solutions/$slug': typeof SiteSolutionsSlugRoute
  '/app/assignments/$assignmentId': typeof AppAssignmentsAssignmentIdRoute
  '/app/classes/$classId': typeof AppClassesClassIdRoute
  '/app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/customer-stories': typeof SiteCustomerStoriesRoute
  '/api/$': typeof ApiSplatRoute
  '/': typeof SiteIndexRoute
  '/app': typeof AppIndexRoute
  '/products/$slug': typeof SiteProductsSlugRoute
  '/solutions/$slug': typeof SiteSolutionsSlugRoute
  '/app/assignments/$assignmentId': typeof AppAssignmentsAssignmentIdRoute
  '/app/classes/$classId': typeof AppClassesClassIdRoute
  '/app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/customer-stories': typeof SiteCustomerStoriesRoute
  '/api/$': typeof ApiSplatRoute
  '/_site/': typeof SiteIndexRoute
  '/app/': typeof AppIndexRoute
  '/_site/products/$slug': typeof SiteProductsSlugRoute
  '/_site/solutions/$slug': typeof SiteSolutionsSlugRoute
  '/app/assignments/$assignmentId': typeof AppAssignmentsAssignmentIdRoute
  '/app/classes/$classId': typeof AppClassesClassIdRoute
  '/app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/about'
    | '/contact'
    | '/customer-stories'
    | '/api/$'
    | '/app/'
    | '/products/$slug'
    | '/solutions/$slug'
    | '/app/assignments/$assignmentId'
    | '/app/classes/$classId'
    | '/app/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/about'
    | '/contact'
    | '/customer-stories'
    | '/api/$'
    | '/'
    | '/app'
    | '/products/$slug'
    | '/solutions/$slug'
    | '/app/assignments/$assignmentId'
    | '/app/classes/$classId'
    | '/app/submissions/$submissionId'
  id:
    | '__root__'
    | '/_site'
    | '/app'
    | '/login'
    | '/signup'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/customer-stories'
    | '/api/$'
    | '/_site/'
    | '/app/'
    | '/_site/products/$slug'
    | '/_site/solutions/$slug'
    | '/app/assignments/$assignmentId'
    | '/app/classes/$classId'
    | '/app/submissions/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/customer-stories': {
      id: '/_site/customer-stories'
      path: '/customer-stories'
      fullPath: '/customer-stories'
      preLoaderRoute: typeof SiteCustomerStoriesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/products/$slug': {
      id: '/_site/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof SiteProductsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/solutions/$slug': {
      id: '/_site/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SiteSolutionsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/assignments/$assignmentId': {
      id: '/app/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/app/assignments/$assignmentId'
      preLoaderRoute: typeof AppAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes/$classId': {
      id: '/app/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/app/classes/$classId'
      preLoaderRoute: typeof AppClassesClassIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions/$submissionId': {
      id: '/app/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/app/submissions/$submissionId'
      preLoaderRoute: typeof AppSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteCustomerStoriesRoute: typeof SiteCustomerStoriesRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProductsSlugRoute: typeof SiteProductsSlugRoute
  SiteSolutionsSlugRoute: typeof SiteSolutionsSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteCustomerStoriesRoute: SiteCustomerStoriesRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProductsSlugRoute: SiteProductsSlugRoute,
  SiteSolutionsSlugRoute: SiteSolutionsSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAssignmentsAssignmentIdRoute: typeof AppAssignmentsAssignmentIdRoute
  AppClassesClassIdRoute: typeof AppClassesClassIdRoute
  AppSubmissionsSubmissionIdRoute: typeof AppSubmissionsSubmissionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAssignmentsAssignmentIdRoute: AppAssignmentsAssignmentIdRoute,
  AppClassesClassIdRoute: AppClassesClassIdRoute,
  AppSubmissionsSubmissionIdRoute: AppSubmissionsSubmissionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
